name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Descargando Repositorio
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Instalando NodeJS v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Instalando Dependencias
        run: npm install --no-audit --no-fund --no-optional
      - name: Ejectuando Chequeo de Codigo (LINT)
        run: npm run lint
      - name: Empaquetando Aplicacion (BUILD)
        run: npm run build
      - name: Desplegando en HEROKU (DEPLOY)
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          healthcheck: 'https://${{secrets.HEROKU_APP}}/health'
