name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-18.04
    permissions:
      actions: write
    steps:
      - name: Cancelando Compilaciones Anteriores Redundantes
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}

  install:
    runs-on: ubuntu-18.04
    steps:
      - name: Descargando Repositorio
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Instalando NodeJS v16
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Instalando Dependencias
        run: npm install

  lint:
    needs: [install]
    runs-on: ubuntu-18.04
    steps:
      - name: Descargando Repositorio
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Instalando NodeJS v16
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Instalando Dependencias
        run: npm install
      - name: Ejectuando Chequeo de Codigo (LINT)
        run: npm run lint

  build:
    needs: [install]
    runs-on: ubuntu-18.04
    steps:
      - name: Descargando Repositorio
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Instalando NodeJS v16
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Instalando Dependencias
        run: npm install
      - name: Empaquetando Aplicacion (BUILD)
        run: npm run build
      # - name: Guardando Artefacto (BUILD)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: lib
      #     path: lib

  deploy:
    needs: [lint, build]
    runs-on: ubuntu-18.04
    steps:
      - name: Descargando Repositorio
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Desplegando en HEROKU (DEPLOY)
        if: ${{github.event_name == 'push'}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          # healthcheck: 'https://${{secrets.HEROKU_APP}}.herokuapp.com/health'
          # rollbackonhealthcheckfailed: true
          delay: 5
