name: Deployment Pipeline

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Instalando Dependencias
        run: npm install --no-audit --no-fund --no-optional
      - name: Ejectuando Chequeo de Codigo (LINT)
        run: npm run lint
      - name: Empaquetando Aplicacion (BUILD)
        run: npm run build
